# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [2]:
import numpy as np

In [6]:
np.random.randint(0, 20, size = (4, 7))

array([[ 4, 10, 12, 18,  3,  0, 12],
       [ 0,  8,  6,  4,  2,  1, 11],
       [ 8, 17,  1, 10, 17,  6,  8],
       [ 7,  1,  9, 11,  6, 16, 11]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [7]:
np.random.randint(0, 10, size = (8, 10))

array([[3, 7, 9, 1, 9, 6, 9, 3, 2, 9],
       [7, 8, 9, 7, 8, 3, 1, 5, 3, 9],
       [1, 4, 2, 3, 9, 4, 1, 5, 4, 1],
       [1, 4, 7, 9, 4, 7, 6, 8, 7, 8],
       [0, 9, 4, 7, 8, 4, 5, 2, 4, 6],
       [6, 1, 2, 9, 6, 8, 1, 9, 0, 2],
       [5, 2, 4, 5, 9, 2, 1, 7, 5, 1],
       [9, 2, 8, 5, 1, 4, 7, 9, 6, 2]])

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [10]:
import matplotlib.pyplot as pl
from mpl_toolkits.mplot3d import Axes3D

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

## Лабораторная работа №1

In [38]:
import numpy as np

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [3]:
data = np.loadtxt(
    'data/minutes_n_ingredients.csv',
    skiprows = 1,
    dtype = 'int32',
    delimiter = ',',
)
data[:5]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]], dtype=int32)

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [4]:
print(f'Среднее значение: {np.mean(data[:, 1:2])} Минимум: {data[:, 1:2].min()} Максимум: {data[:, 1:2].max()} Медиана:{np.median(data[:, 1:2])}')
print(f'Среднее значение: {np.mean(data[:, 2])} Минимум: {data[:, 2].min()} Максимум: {data[:, 2].max()} Медиана: {np.median(data[:, 2])}')

Среднее значение: 21601.00169 Минимум: 0 Максимум: 2147483647 Медиана:40.0
Среднее значение: 9.05528 Минимум: 1 Максимум: 39 Медиана: 9.0


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [5]:
max_time = np.quantile(data[:, 1], 0.75)
data[:, 1] = np.clip(data[:, 1], a_min = None,a_max = max_time)

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [6]:
print(np.sum(data[:,1] == 0))
data[:,1][data[:,1] == 0] = 1

479


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [7]:
len(np.unique(data, axis = 0))

100000

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [8]:
print(f'Всего уникальных рецептов: {len(np.unique(data[:, 2]))}')
unique, counts = np.unique(data[:, 2], return_counts = True)
print(np.asarray((unique, counts)). T)

Всего уникальных рецептов: 37
[[    1    13]
 [    2   926]
 [    3  2895]
 [    4  5515]
 [    5  7913]
 [    6  9376]
 [    7 10628]
 [    8 10951]
 [    9 10585]
 [   10  9591]
 [   11  8297]
 [   12  6605]
 [   13  4997]
 [   14  3663]
 [   15  2595]
 [   16  1767]
 [   17  1246]
 [   18   790]
 [   19   573]
 [   20   376]
 [   21   217]
 [   22   161]
 [   23   105]
 [   24    69]
 [   25    50]
 [   26    28]
 [   27    16]
 [   28    16]
 [   29    12]
 [   30    12]
 [   31     3]
 [   32     1]
 [   33     2]
 [   34     1]
 [   35     3]
 [   37     1]
 [   39     1]]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [9]:
data_2 = data[data[:,2] <= 5]
print(data_2.shape)
print(data_2[:5])

(17262, 3)
[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 [484223     18      4]
 [ 63150     65      4]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [12]:
np.max(np.array(data[:,2]/data[:,1]))

24.0

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [107]:
u, idx = np.unique(data, axis=0, return_index=True)
res = u[idx.argsort()]
x_sorted_desc = res[res[:, 1].argsort()[::-1]]
print(np.mean(x_sorted_desc[:100,2]))

9.96


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [18]:
index = np.random.randint(0, len(data), 10)
print(data[index])

[[216627     65     11]
 [143317     45      3]
 [ 45285     45      9]
 [433805     45      9]
 [399668     65      8]
 [184704     15     19]
 [200143     40     10]
 [236742     30     10]
 [119123     65     10]
 [175797     65      8]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [108]:
count_ingr = np.sum([data[:, 2] < np.mean(data[:, 2])])
print((count_ingr / len(data) * 100))

58.802


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [33]:
simple_recipe = (data[:, 1] <= 20) & (data[:, 2] <= 5)
data_simple_recipe = np.insert(data, 3, np.where(simple_recipe, 1, 0), axis=1)

print(data_with_simple_flag[:5])

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 [ 67660      5      6      0]
 [157911     60     14      0]]


13. Выведите процент "простых" рецептов в датасете

In [34]:
print((len(data_3) / len(data)) * 100)

9.552


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [37]:
short = data[:,1] < 10
standard = (data[:, 1] >= 10) & (data[:, 1] < 20)
long = data[:,1] >= 20

max_short = np.count_nonzero(short)
max_standard = np.count_nonzero(standard)
max_long = np.count_nonzero(long)

result = result_array = np.zeros((3, max_long, data.shape[1]), dtype=np.int32)

result[0, :max_short, :] = data[short]
result[1, :max_standard, :] = data[standard]
result[2, :max_long, :] = data[long]

print(result.shape)

(3, 79751, 3)
